FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y \
    curl \
    gnupg \
    git \
    build-essential \
    libssl-dev \
    libffi-dev \
    ca-certificates && \
    curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

ENV DEBIAN_FRONTEND=noninteractive
ENV CHOKIDAR_USEPOLLING=true

# EXPOSE 3000

# CMD ["npm", "run", "dev"]